# Generated by Django 3.2.7 on 2021-09-13 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210913_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeimage',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=20),
        ),
    ]
