# Generated by Django 3.2.7 on 2021-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210913_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerimage',
            options={'verbose_name': 'Customer image', 'verbose_name_plural': 'Customer images'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeimage',
            options={'verbose_name': 'Employee image', 'verbose_name_plural': 'Employee images'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
