# Generated by Django 3.2.7 on 2021-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210913_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='identity_code',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
