# Generated by Django 3.2.7 on 2021-09-27 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_shopuser_identity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='identity_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_entity_code', message='entity code must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number is invalid', regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')]),
        ),
    ]
