# Generated by Django 3.2.7 on 2021-09-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'Discount code', 'verbose_name_plural': 'Discount codes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'Order history', 'verbose_name_plural': 'Orders history'},
        ),
        migrations.AlterModelOptions(
            name='orderrow',
            options={'verbose_name': 'Order row', 'verbose_name_plural': 'Order rows'},
        ),
    ]
