# Generated by Django 3.2.8 on 2021-11-22 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 18, 26, 49, 318237, tzinfo=utc), verbose_name='order date'),
        ),
    ]
