# Generated by Django 3.2.8 on 2021-11-17 16:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=250, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(max_length=500, upload_to='products/advertising/%Y/%m/%d/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Advertising',
                'verbose_name_plural': 'Advertisings',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=250, verbose_name='name')),
                ('name_en', models.CharField(max_length=250, verbose_name='name')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, verbose_name='values'), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=250, verbose_name='name')),
                ('name_en', models.CharField(max_length=250, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='image')),
                ('title_en', models.CharField(max_length=100, verbose_name='image')),
                ('image', models.ImageField(max_length=500, upload_to='products/%Y/%m/%d/', verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=250, verbose_name='name')),
                ('name_en', models.CharField(max_length=250, verbose_name='name')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_products', models.PositiveIntegerField(default=0, verbose_name='number of products')),
                ('attributes', models.ManyToManyField(to='products.Attribute', verbose_name='Attributes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category')),
                ('images', models.ManyToManyField(related_name='images', to='products.ProductImage', verbose_name='images')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
