# Generated by Django 3.2.7 on 2021-09-27 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210913_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
